#
# SaveCoreV5
# Developed by Save#5636
#
# All message support hex in the &<hex> format. Adventure is a WIP
#


commands:
  #This is the command name. This command for example is /twitter.
  twitter:
    #The message sent when the user runs the commands. Supports PlaceholderAPI
    message:
      - "<yellow><bold>[!] TWITTER</bold>"
      - "<gold><bold>*</bold> <white>Follow us on twitter <yellow>@ItzSave"


#Create and edit your announcements.
#If messages are centered they do not support PlaceholderAPI!
Announcements:
  Discord:
    Message:
      - '<aqua>This is an example announcement <gray>(#1)'
  Twitter:
    Message:
      - '<red>This is an example announcement <gray>(#2)'

#Message sent when /donation is run.
Donation-Announcement:
  - '<green>%player% has donated at store.itzsave.org'

Settings:
  #Disables or enables the custom commands located at the top of this file.
  custom-commands-enabled: true

  #Enables the automatic announcements.
  enable-announcer: true

  #Centers the announcement messages.
  center-announcements: false

  #Disables or enables custom join message.
  join-message-enabled: false

  #Disables or enables custom leave messages.
  leave-message-enabled: false

  #Time between messages in seconds.
  announcer-interval: 600

  #Disables wither spawning.
  disable-wither-spawns: true

  #Enables the ability to change spawner type with an egg.
  eggs-change-spawners: false

  #Enables or disables raid farms.
  anti-raid-farm: false

  # How many seconds must a player wait between starting raids
  # Give the permission `saveutil.raidfarmbypass` to players you wish to bypass this
  raid-cooldown-seconds: 180