#
# SaveUtils
# Developed by Save#5636
#
# Placeholders:
# %saveutils_exp% - Returns formatted experience.
#
# Permissions
# saveutils.nightvision - Gives access to /nightvision
# saveutils.admin - Gives access to admin functions such as /reload.
# saveutils.raidfarmbypass - Allows users to bypass raid farm cooldown
# saveutils.autotrash - Allows users to use the autotrash features.

# Enable or disable various features of the plugin.
Modules:
  # Enables the purpur config options found below.
  # WARNING: You must be running purpur, or you will have errors or crashes.
  enable-purpur-settings: false

  # Enable or disable the ability to define custom commands.
  custom-commands-enabled: true

  # Enables a message that displays the percentage of users online that are sleeping.
  enable-sleep-listener: true

  # Enables the automatic announcements.
  enable-announcer: false

  # Enables the ability for SaveUtils to handle chat formatting.
  enable-chat-formatting: true

  # Prevents users from dying due to the void. NOTE: Teleports to the user to the spawn location of the world they are currently in.
  enable-anti-void-death: true

  # Disable phantom spawning.
  disable-phantom-spawning: true

  # Disable wither spawning
  disable-wither-spawning: true

  #Enables or disables raid farms.
  disable-raid-farms: false

#This requires the server to be running Purpur in order to work. https://purpurmc.org/
Purpur-Settings:
  #Gives a user an enchantment book of the enchantment(s) removed from the item.
  give-books-when-grindstone-disenchant: false

#Various settings for different modules
Settings:

  #Time between messages in seconds.
  announcer-interval: 600

  disable-join-messages: false
  disable-quit-messages: false

  # How many seconds must a player wait between starting raids
  # Give the permission `saveutil.raidfarmbypass` to players you wish to bypass this
  raid-cooldown-seconds: 180


# Chat formatting Placeholders:
# The content of the message is added at the end.
#
# {name} - the player's name
# {displayname} - the player's display name / nickname
# {prefix} - the player's highest priority prefix
# {suffix} - the player's highest priority suffix
#
Chat-Formats:
  default: "{prefix}{name}: "

  # Set the format per group.
  group-formats:
  #  default: "[Default] {name}: "
  #  admin: "[Admin] {name}: "

Custom-Commands:
  #This is the command name. This command for example is /twitter.
  twitter:
    #The message sent when the user runs the commands. Supports PlaceholderAPI
    message:
      - "<yellow><bold>[!] TWITTER</bold>"
      - "<gold><bold>*</bold> <white>Follow us on twitter <yellow>@ItzSave"


#Create and edit your announcements.
Announcements:
  Discord:
    Message:
      - '<aqua>This is an example announcement <gray>(#1)'
  Twitter:
    Message:
      - '<red>This is an example announcement <gray>(#2)'

#Message sent when /donation is run.
Donation-Announcement:
  - '<green>%player% has donated at store.itzsave.org'
