name: SaveUtils
version: '${version}'
authors: [Save]
main: org.itzsave.SaveUtils
api-version: 1.19
dependencies:
  - name: LuckPerms
    required: false
  - name: PlaceholderAPI
    required: false
permissions:
  saveutils.admin:
    description: Gives access to admin commands.
    default: op
    children:
      - saveutils.silent
      - saveutils.raidfarmbypass
  saveutils.slient:
    description: Allows users to join sliently.
  saveutils.raidfarmbypass:
    description: Allows users to disable raid farm cooldown.
  saveutils.nightvision:
    description: Allows the user to use the nightvision command.
