name: SaveUtils
version: '${version}'
main: org.itzsave.SaveUtils
api-version: 1.19
softdepend: [ PlaceholderAPI, LuckPerms ]
authors: [ ItzSave ]
description: Simple utility plugin to add various features/adjustments.

permissions:
  saveutil.slient:
    description: Allows users to join sliently.
  saveutil.raidfarmbypass:
    description: Allows users to disable raid farm cooldown.