name: SaveUtils
version: '${version}'
main: org.itzsave.SaveUtils
api-version: 1.18
softdepend: [ PlaceholderAPI ]
authors: [ ItzSave ]
description: Simple ultily plugin to add random features/adjustments.

commands:
  saveutil:
    description: Main command.
  nightvision:
    description: Enables or disables a users nightvision effect.
  rules:
    description: Displays a list of rules.
    aliases: [ rule ]
  donation:
    description: Used to send a configured message when a user donates.
  autotrash:
    aliases: [ at ]
    description: Access to the auto trash system

permissions:
  saveutil.admin:
    description: Access to all admin related commands & features.
  saveutil.nightvision:
    description: Gives access to /nightvision.
  saveutil.slient:
    description: Allows users to join sliently.
  autotrash.use:
    description: Allows users to access the auto trash feature.